name: sign_experiment
data:
    data_path: ./data/
    version: Auslan_Daily
    sgn: sign
    txt: text
    gls: gloss
    train: SP_S_s16s2/train.pkl
    dev: SP_S_s16s2/val.pkl
    test: SP_S_s16s2/test_feature.pkl
    feature: RGB
    level: word
    txt_lowercase: true
    max_sent_length: 500
    random_train_subset: -1
    random_dev_subset: -1
testing:
    recognition_beam_sizes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    translation_beam_sizes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    translation_beam_alphas:
    - -1
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
training:
    reset_best_ckpt: false
    reset_scheduler: false
    reset_optimizer: false
    random_seed: 43
    model_dir: "./sign_SP_RGB_Trans_E3D3/"
    recognition_loss_weight: 0.0
    translation_loss_weight: 1.0
    eval_metric: bleu
    optimizer: adam
    learning_rate: 0.00005
    batch_size: 64
    num_valid_log: 0
    epochs: 100
    early_stopping_metric: eval_metric
    batch_type: sentence
    translation_normalization: batch
    eval_recognition_beam_size: 1
    eval_translation_beam_size: 1
    eval_translation_beam_alpha: -1
    overwrite: true
    shuffle: true
    use_cuda: true
    translation_max_output_length: 50
    keep_last_ckpts: 1
    batch_multiplier: 1
    logging_freq: 100
    validation_freq: 100
    betas:
    - 0.9
    - 0.998
    scheduling: plateau
    learning_rate_min: 1.0e-07
    weight_decay: 0.001
    patience: 8
    decrease_factor: 0.9
    label_smoothing: 0.1
model:
    initializer: xavier
    bias_initializer: zeros
    init_gain: 1.0
    embed_initializer: xavier
    embed_init_gain: 1.0
    tied_softmax: false
    encoder:
        type: transformer
        num_layers: 3
        num_heads: 8
        embeddings:
            embedding_dim: 1024
            scale: false
            dropout: 0.1
            norm_type: batch
            activation_type: softsign
        hidden_size: 1024
        ff_size: 2048
        dropout: 0.2
    decoder:
        type: transformer
        num_layers: 3
        num_heads: 8
        embeddings:
            embedding_dim: 1024
            scale: false
            dropout: 0.1
            norm_type: batch
            activation_type: softsign
        hidden_size: 1024
        ff_size: 2048
        dropout: 0.2